### ISSUE TITLE
No such file or directory during Build binaries non-Web

### ISSUE THREAD

**Issue by davidromani** [TheBevyFlock/bevy_new_2d#316]
I'm trying to build Windows & Linux binaris and always ended up with same results:

```bash
Compiling my_app v0.1.0 (/home/runner/work/My-Repositoy-Project-Name/My-Repositoy-Project-Name)
 Finished `release-native` profile [optimized] target(s) in 12m 13s
mv: cannot stat 'target/x86_64-unknown-linux-gnu/release-native/my_app': No such file or directory
Error: Process completed with exit code 1.
```

I've checked the `.github/workflows/release.yaml` env variables and it seems that are well configured. What I suspect is that the problem is due to my GitHub repository project name (My-Repositoy-Project-Name) doesn't match with the names (my_app) defined here:

```yaml
env:
  cargo_build_binary_name: my_app
  assets_path: assets
  upload_to_github: true
  upload_to_itch: my_itch_user/my-app
  app_id: my_itch_user.my-app
  app_binary_name: my_app
```

**Comment by benfrankel** [comment]
What is the name of the binary produced when you run `cargo build` locally?

**Comment by davidromani** [comment]
@benfrankel in Windows, seems `target\debug\main.exe`

**Comment by benfrankel** [comment]
In that case, `cargo_build_binary_name` should be set to `main`.

Do you know why cargo build is producing that binary name instead of `my_app.exe`? It would depend on how your project is set up, so I would need more information to know if this is an issue with `bevy_new_2d`'s CI, its docs, or an issue with `cargo`, or not an issue.

**Comment by davidromani** [comment]
my Cargo.toml config sets this name:

```toml
[package]
name = "my_app"
```

do you need to see more config files?
