### ISSUE TITLE
Profile config inheritance get's in the way

### ISSUE THREAD

**Issue by adsick** [TheBevyFlock/bevy_new_2d#435]
Real world example: crate `bevy_spatial` does not build to wasm by default, in order to bulid it I  have to disable default features and enable `kdtree` feature.
So I want to enable `default` on native, but also enable just `kdtree` on web.
Since web __for some reason__ [inherits](https://thebevyflock.github.io/bevy_cli/cli/configuration.html?highlight=metadata#configuration) from native that doesn't seem to be possible.

```toml

[features]
...
bevy_spatial = { version = "0.11.0", default-features = false }

[package.metadata.bevy_cli.dev]
features = ["dev", "bevy_spatial/default"]

[package.metadata.bevy_cli.release]
# Disable dev features for release builds.
# TODO: switch to false before publish
default-features = true
features = ["bevy_spatial/default"]

[package.metadata.bevy_cli.web]
# Disable native features for web builds.
default-features = false
features = ["bevy_spatial/kdtree"]

[package.metadata.bevy_cli.web.dev]
features = ["dev", "bevy_spatial/kdtree"]
```

And even then it looks pretty confusing but I guess we are left with what we have here)

**Comment by benfrankel** [comment]
I don't think web inherits from native? It does inherit from dev, if that's what you mean?

I would expect something like this to work:

```toml
[package.metadata.bevy_cli.native]
features = ["bevy_spatial/default"]

[package.metadata.bevy_cli.web]
features = ["bevy_spatial/kdtree"]
```

Unless I'm missing something.

I do think the current feature setup in `bevy_new_2d` is confusing due to `default-features` and, in the name of simplicity, fails to provide users with a place for features that should only be enabled in native builds, or only in web builds, or only in web dev builds -- which tend to come up as you add 3rd-party dependencies. In my personal template for example, I already have a feature set up for each of these, and I have no `default` features.

Also, related: https://github.com/TheBevyFlock/bevy_new_2d/issues/186.
