### ISSUE TITLE
Add magic incantation to Wasm build

### ISSUE THREAD

**Issue by janhohenheim** [TheBevyFlock/bevy_new_2d#442]
```toml
[target.wasm32-unknown-unknown]
rustflags = "-C target-feature=+bulk-memory,+sign-ext,+nontrapping-fptoint"
```
Search Discord for `bulk-memory` and you'll see a few people using this. No idea what it does, but it sped up our submission.
